#CREATE schema WatchaDoingDB;

USE WatchaDoingDB;

CREATE TABLE Watch(
	id INT AUTO_INCREMENT PRIMARY KEY,
	createdAt DATETIME NOT NULL,
	updatedAt DATETIME NOT NULL,
	model VARCHAR(100) NOT NULL,
	origin VARCHAR(40) NOT NULL,
    price DECIMAL(12, 2) NOT NULL,
    sn VARCHAR(20) NOT NULL,
    quantity INT NOT NULL DEFAULT 0,
	isDeleted BOOLEAN NOT NULL DEFAULT FALSE
);
	
CREATE TABLE Category(
	id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(20) NOT NULL,
	createdAt DATETIME NOT NULL,
	updatedAt DATETIME NOT NULL,
	description VARCHAR(255),
	isDeleted BOOLEAN NOT NULL DEFAULT FALSE
);
  
CREATE TABLE Customer (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(70) NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    isDeleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE OrderShipment (
    id INT AUTO_INCREMENT PRIMARY KEY,
    trackingNum VARCHAR(13) NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE WatchOrder (
    id INT AUTO_INCREMENT PRIMARY KEY,
    customerId INT NOT NULL,
    shipmentId INT UNIQUE,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (customerId) REFERENCES Customer(id) ON DELETE CASCADE,
    FOREIGN KEY (shipmentId) REFERENCES OrderShipment(id) ON DELETE SET NULL
);

CREATE TABLE WatchOrderLine (
    id INT AUTO_INCREMENT PRIMARY KEY,
    quantity INT DEFAULT 0,
    watchId INT NOT NULL,
    orderId INT NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (watchId) REFERENCES Watch(id) ON DELETE CASCADE,
    FOREIGN KEY (orderId) REFERENCES WatchOrder(id) ON DELETE CASCADE
);

DROP Table WatchOrderLine;
DROP Table WatchOrder;
DROP Table OrderShipment;
DROP Table Customer;

